export const questionsData = {
  'TON Ecosystem': {
    q1: {
      id: 1,
      title: 'Question',
      questionTitle: 'WHAT IS TON?',
      answers: [
        'Total Online Network',
        'Trusted Object Network',
        'The Original Network',
        'The Open Network',
      ],
      correctAnswer: 'The Open Network',
    },
    q2: {
      id: 2,
      title: 'Question',
      questionTitle: 'WHAT IS THE OPEN NETWORK(TON)?',
      answers: [
        'It is a Telegramm Shop',
        'A subscription that you can make in Telegramm',
        'It is a Telegramm Wallet',
        'It is a Blockchain',
      ],
      correctAnswer: 'It is a Blockchain',
    },
    q3: {
      id: 3,
      title: 'Question',
      questionTitle: 'Does TON have a test environment?',
      answers: [
        'Yes',
        'No',
        'Yes, but need Telegram Premium',
        'Yes, but need 1000 Telegram Stars',
      ],
      correctAnswer: 'Yes',
    },
    q4: {
      id: 4,
      title: 'Question',
      questionTitle: 'When The First Block in TON was Mined?',
      answers: ['In 2009', 'In 2020', 'It will happen in the future', 'Today'],
      correctAnswer: 'In 2020',
    },
    q5: {
      id: 5,
      title: 'Question',
      questionTitle:
        'What is the name of the token used in the TON Blockchain?',
      answers: ['BitTON', 'EtherTon', 'Toncoin', 'Telecoin'],
      correctAnswer: 'Toncoin',
    },
    q6: {
      id: 6,
      title: 'Question',
      questionTitle: 'What is the purpose of the TON Blockchain?',
      answers: [
        'Only for storing videos',
        'Creating decentralized applications',
        'Developing video games',
        'Only for Bitcoin mining',
      ],
      correctAnswer: 'Creating decentralized applications',
    },
    q7: {
      id: 7,
      title: 'Question',
      questionTitle: 'How does TON differ from other blockchains?',
      answers: [
        'It is a multi-blockchain with high transaction speed',
        'It is a centralized network',
        "It doesn't have its own token",
        'It only works in the USA',
      ],
      correctAnswer: 'It is a multi-blockchain with high transaction speed',
    },
  },
  Founders: {
    q1: {
      id: 1,
      title: 'Question',
      questionTitle: 'Who is Satoshi Nakamoto?',
      answers: [
        'Creator of Ethereum Whitepaper',
        'Popular famous football player',
        'Popular famous actor',
        'Creator of Bitcoin Whitepaper',
      ],
      correctAnswer: 'Creator of Bitcoin Whitepaper',
    },
    q2: {
      id: 2,
      title: 'Question',
      questionTitle: 'Who is Vitalii Buterin?',
      answers: [
        'Creator of Binance Smart Chain',
        'Creator of Solana Blockchain',
        'Creator of Ethereum Blockchain',
        'Creator of TON',
      ],
      correctAnswer: 'Creator of Ethereum Blockchain',
    },
    q3: {
      id: 3,
      title: 'Question',
      questionTitle: 'Who is Pavel Durov?',
      answers: [
        'Creator of Binance Smart Chain',
        'Creator of Solana Blockchain',
        'Creator of Ethereum Blockchain',
        'Creator of Telegram',
      ],
      correctAnswer: 'Creator of Telegram',
    },
  },
  Security: {
    q1: {
      id: 1,
      title: 'Question',
      questionTitle: 'What is Seed Phrase?',
      answers: [
        'Data required to access crypto',
        'Book love story',
        'This are the traffic rules',
        'This is a popular joke',
      ],
      correctAnswer: 'Data required to access crypto',
    },
    q2: {
      id: 2,
      title: 'Question',
      questionTitle: 'What is Whitepaper?',
      answers: [
        'Paper from the white house of the president',
        'Old pirate treasure map',
        'Receipt of payment in cryptocurrency',
        'Technology, product or service  documentation',
      ],
      correctAnswer: 'Technology, product or service  documentation',
    },
    q3: {
      id: 3,
      title: 'Question',
      questionTitle: 'What is Smart Contract?',
      answers: [
        'This is a contract to kill in the game',
        'This is a new action-packed detective story',
        'Сontract that football players sign',
        'Computer program that works ib Blockchain',
      ],
      correctAnswer: 'Computer program that works ib Blockchain',
    },
    q4: {
      id: 4,
      title: 'Question',
      questionTitle: 'It is Possible To Know All Private Keys?',
      answers: [
        'It is not possible',
        'It is possible, but need more than 1 000 000+ Years',
        'It is possible, need 1 Year',
        'It is already in Internet',
      ],
      correctAnswer: 'It is possible, but need more than 1 000 000+ Years',
    },
    q5: {
      id: 5,
      title: 'Question',
      questionTitle: 'What is Blockchain?',
      answers: [
        'Digital database',
        'Anchor chain on a ship',
        'Jewelry for the neck',
        'It is a Bitcoin',
      ],
      correctAnswer: 'Digital database',
    },
    q6: {
      id: 6,
      title: 'Question',
      questionTitle: 'What is inflation in cryptocurrency?',
      answers: [
        'It is a Blockchain',
        'When The number of coins increases',
        'It is a Game',
        'When The the crypto is swap',
      ],
      correctAnswer: 'When The number of coins increases',
    },
    q7: {
      id: 7,
      title: 'Question',
      questionTitle: 'What is Cryptocurrency?',
      answers: [
        'It is a Blockchain',
        'Сoins that were hunted by pirates',
        'It is a Fruit',
        'Digital currency for exchange on computer network',
      ],
      correctAnswer: 'Digital currency for exchange on computer network',
    },
    q8: {
      id: 8,
      title: 'Question',
      questionTitle: 'What is Play To Earn(P2E)?',
      answers: [
        "This is a child's game",
        'This is an old pirate tale',
        'This is a game in the movie Harry Potter',
        'Gaming Model',
      ],
      correctAnswer: 'Gaming Model',
    },
    q9: {
      id: 9,
      title: 'Question',
      questionTitle: 'What is AirDrop in Crypto?',
      answers: [
        'It is Cryptocurrency Coin Burning',
        'It is Crypto Trading Stratagy',
        'It is Crypto Game',
        'When crypto sent to the wallets of active members',
      ],
      correctAnswer: 'When crypto sent to the wallets of active members',
    },
    q10: {
      id: 10,
      title: 'Question',
      questionTitle: 'What is Public Key?',
      answers: [
        'It is name of Crypto Hacker',
        'It is Crypto Trading Stratagy',
        'It is Refferal Link in Crypto Game',
        'It is part of Blockchain Security and cryptography',
      ],
      correctAnswer: 'It is part of Blockchain Security and cryptography',
    },
  },
  Another: {
    q1: {
      id: 1,
      title: 'Question',
      questionTitle: 'What is Ethereum?',
      answers: [
        'It is an island on a earth',
        'It is a Fruit',
        'This is a female name',
        'Blockchain with smart contract functionality',
      ],
      correctAnswer: 'Blockchain with smart contract functionality',
    },
    q2: {
      id: 2,
      title: 'Question',
      questionTitle: 'What are crypto whales?',
      answers: [
        'Individuals that hold large amounts of crypto',
        'Crypto Game Characters',
        'It is Large Transaction in Crypto',
        'It is Crypto Coin Price Dump',
      ],
      correctAnswer: 'Individuals that hold large amounts of crypto',
    },
    q3: {
      id: 3,
      title: 'Question',
      questionTitle: 'What is Mining in Blockchain?',
      answers: [
        'This is a crypto wallet',
        'This is blockchain hack',
        'This is cryptocurrency',
        'Transaction record process in blockchain',
      ],
      correctAnswer: 'Transaction record process in blockchain',
    },
  },
};
